controllers/HomeController.php
<?php
/**
 * Created by PhpStorm.
 * User: zhenj
 * Date: 21.07.2017
 * Time: 14:35
 */

namespace app\controllers;

use app\models\Feedback;
use app\models\Orders;
use app\models\RedactionText;
use app\models\Sliders;
use app\models\SubscriptionNews;
use app\models\Transactions;
use app\models\User;
use Codeception\Lib\Interfaces\ActiveRecord;
use yii\behaviors\TimestampBehavior;
use yii\data\ActiveDataProvider;
use app\models\Posts;
use app\models\Reviews;
use Yii;
use yii\helpers\StringHelper;
use yii\web\UploadedFile;
use yii\data\Pagination;
class HomeController extends BehaviorsController
{

    public function actionNews(){

        $query = Posts::find();
        $pages = new Pagination(['totalCount'=> $query->count(), 'pageSize'=>5,
          'forcePageParam' => false, 'pageSizeParam' => false]);
        $news  = $query->offset($pages->offset)->limit($pages->limit)->all();
        $model = Posts::find()->orderBy(['date' =>SORT_DESC])->all();
        return $this->render('news', compact('news','pages','model'));
    }

    public function actionRedactionText(){

        $redaction = RedactionText::find()->where(['id' => 1])->one();
        if ($redaction->load(Yii::$app->request->post())) {
            $redaction->text;
            $redaction->save();
            $this->refresh();
        }else {
            false;
        }
        return $this->render('redaction-text',compact('redaction'));
    }
    public function actionSortNews($id){
        $this->layout=false;

        $model = Posts::findOne($id);

        return $this->render('sort-news', compact('model'));
    }

    public function actionPersonalArea(){
        $this->view->title = Yii::t('common','Личный кабинет');
        $user = User::find()->select('email')->all();
        $sub_news = SubscriptionNews::find()->where(['email' => $user])->one();
        if ($sub_news == null)
        {
            $is_subNews = 0;
        }
        else{
            $is_subNews = 1;
        }
        $sub_news_save = new SubscriptionNews();
        if ($sub_news_save->load(Yii::$app->request->post())){
            if ($sub_news_save->save()){
                $sub_news_save->email = \Yii::$app->mailer->compose()
                    ->setTo('zhenja1509@gmail.com')
                    ->setFrom('zhenja94@bk.ru')
                    ->setSubject('Подписка на новости')
                    ->setTextBody("На ваши новости подписался " .$sub_news->email)
                    ->send();
            }
            $this->refresh();
        }
        $order = new Orders();
        if($order->load(Yii::$app->request->post())) {
            $order->is_user = Yii::$app->user->identity->id;
            if(!isset($_POST['is_confirm'])){
                Yii::$app->session->setFlash('error', 'Вы не согласились на обработку данных.');
                return $this->refresh();
            }
            if($order->save()){
                Yii::$app->session->setFlash('success', 'Спасибо, ваша заявка принята.');
                $order->email = \Yii::$app->mailer->compose()
                    ->setTo('zhenja1509@gmail.com')
                    ->setFrom('zhenja94@bk.ru')
                    ->setSubject('Заявка на '. $order->type)
                    ->setTextBody("Пользователь $order->name,  email: $order->email, телефон: $order->phone оставил заявку на: 
                        $order->type,  платежной системой $order->payment_system")
                    ->send();
                return $this->refresh();
            }
            else{
                Yii::$app->session->setFlash('error', 'Ошибка');
            }
            $this->refresh();
        }
        $history_orders = new ActiveDataProvider([
            'query' => Orders::find()->where(['is_user' => Yii::$app->user->identity->id]),
            'pagination' => [
                'pageSize' => 5,
            ],
        ]);

        return $this->render('personal-area',compact('history_orders','is_subNews','sub_news_save','order'));
    }


    public function actionAdminPanel(){
        $this->view->title = "Панель админа";
        $subNews = new ActiveDataProvider([
            'query' => SubscriptionNews::find(),
            'pagination' => [
                'pageSize' => 5,
            ],
        ]);
        $feedBack = new ActiveDataProvider([
            'query' => FeedBack::find(),
            'pagination' => [
                'pageSize' => 5,
            ],
        ]);
        $orders = new ActiveDataProvider([
            'query' => Orders::find()->with('user'),
            'pagination' => [
                'pagesize' => 10,
            ],
        ]);

        $transactions = new ActiveDataProvider([
            'query' => Transactions::find(),
            'pagination' => [
                'pagesize' => 10,
            ],
        ]);


        return $this->render('admin-panel',compact('subNews','orders', 'transactions', 'feedBack'));
    }
    public function actionDeleteOrders($id){
        $orders = Orders::findOne($id)->delete();
        $this->redirect('/home/admin-panel');
    }
    public function actionDeleteFeedback($id){
        $feedBack = FeedBack::findOne($id)->delete();
        $this->redirect('/home/admin-panel');
    }
    public function actionDeleteSubnews($id){
        $subNews = SubscriptionNews::findOne($id)->delete();
        $this->redirect('/home/admin-panel');
    }
    public function actionDeleteTransactions($id){
        $transactions = Transactions::findOne($id)->delete();
        $this->redirect('/home/admin-panel');
    }
    public function actionAddPosts(){
        $posts = new Posts();
        $users = User::find()->select('email')->all();
        if ($posts->load(Yii::$app->request->post())) {
            if(Yii::$app->request->isPost){
                $posts->image = UploadedFile::getInstance($posts, 'image');
                $posts->date = Yii::$app->formatter->asDate(date('Y-m-d'));
                $posts->image = $posts->upload();
            }
            if($posts->save()){
                Yii::$app->session->setFlash('success', 'Новость сохранена.');
            }
            if (isset($_POST['send_out'])){
                foreach ($users as $user){
                Yii::$app->mailer->compose()
                    ->setTo($user->email)
                    ->setFrom('zhenja94@bk.ru')
                    ->setSubject('GreenCash '.$posts->title)
                    ->setTextBody("Вы получили это сообщение так как зарегистрированы на GreenCash. "
                        .strip_tags($posts->text))
                    ->send();
                }
                Yii::$app->session->setFlash('success', 'Новость разослана на email пользователей.');
            }
            $this->refresh();
        }else {
            false;
        }

        return $this->render('add-posts', compact('posts'));
    }


    public function actionAddSliders(){
        $sliders = new Sliders();
        if ($sliders->load(Yii::$app->request->post())) {
            if(Yii::$app->request->isPost){
                $sliders->image = UploadedFile::getInstance($sliders, 'image');
                $sliders->image = $sliders->upload();
            }
            $sliders->save();
            $this->goHome();
        }else {
            false;
        }
        return $this->render('add-sliders',compact('sliders'));
    }
    public function actionUpdateSlider($id){
        $sliders = Sliders::find()->where(['id'=>$id])->one();
        if ($sliders->load(Yii::$app->request->post())) {
            $sliders->save();
            $this->redirect('/home/change-posts');
        }
        else{
            false;
        }
        return $this->render('update-slider',compact('sliders'));
    }
    public function actionDeleteSlider($id){
        $sliders = Sliders::findOne($id)->delete();
         $this->redirect('/home/change-posts');
    }



    public function actionChangePosts(){
        $posts = new ActiveDataProvider([
            'query' => Posts::find(),
            'pagination' => [
                'pagesize' => 5,
            ],
        ]);
         $reviews = new ActiveDataProvider([
            'query' => Reviews::find(),
            'pagination' => [
                'pagesize' => 10,
            ],
        ]);
        $sliders = new ActiveDataProvider([
            'query' => Sliders::find(),
            'pagination' => [
                'pagesize' => 10,
            ],
        ]);
        return $this->render('change-posts', compact('posts','reviews','sliders'));
    }

    public function actionAddReviews(){
        $reviews = new Reviews();
        if ($reviews->load(Yii::$app->request->post())){
            $reviews->save();
            $this->redirect('/home/admin-panel');
        }
        return $this->render('add-reviews', compact('reviews'));
    }
     public function actionDeletePosts($id){
        $posts = Posts::findOne($id)->delete();
        $this->redirect('/home/change-posts');

     }
     public function actionDeleteReviews($id){
        $reviews = Reviews::findOne($id)->delete();
        $this->redirect('/home/change-posts');
     }
     public function actionUpdateReviews($id){
        $reviews = Reviews::find()->where(['id'=>$id])->one();
        if ($reviews->load(Yii::$app->request->post())) {
            $reviews->save();
            $this->redirect('/home/change-posts');
        }
        else{
            false;
        }
        return $this->render('update-reviews', compact('reviews'));
     }
    public function actionUpdatePosts($id){
        $posts = Posts::find()->where(['id' => $id])->one();
        if ($posts->load(Yii::$app->request->post())) {

controllers/PageController.php
<?php
/**
 * Created by PhpStorm.
 * User: zhenj
 * Date: 09.08.2017
 * Time: 12:50
 */

namespace app\controllers;


use app\models\Feedback;
use app\models\Orders;
use app\models\Posts;
use app\models\RedactionText;
use app\models\User;
use Codeception\Module\Yii2;
use Yii;
use yii\data\Pagination;
use yii\web\Controller;

class PageController extends BehaviorsController
{
    public $layout = '@app/views/layouts/exchanger.php';

    public function actionReplenish(){
        $replenish = new Orders();
        $text_pm = RedactionText::find()->select('payment_system')->one();
        if($replenish->load(Yii::$app->request->post())) {
            $replenish->type = 'Пополнение';
            $replenish->payment_system = $_POST['pay_system'];
            $user = User::find()->where(['email' => $replenish->email])->select(['id','email'])->one();
            if ($user->email != null)
            {
                $replenish->is_user = $user->id;
            }
            else {
                $replenish->is_user = 0;
            }
            if(!isset($_POST['is_confirm'])){
                Yii::$app->session->setFlash('error', 'Вы не согласились на обработку данных.');
                return $this->refresh();
            }
            if($replenish->save()){
                Yii::$app->session->setFlash('success', 'Спасибо, ваша заявка принята.');
                $replenish->email = \Yii::$app->mailer->compose()
                    ->setTo('zhenja1509@gmail.com')
                    ->setFrom('zhenja94@bk.ru')
                    ->setSubject('Заявка на '. $replenish->type)
                    ->setTextBody("Пользователь $replenish->name,  email: $replenish->email, телефон: $replenish->phone оставил заявку на:
                        $replenish->type,  платежной системой $replenish->payment_system")
                    ->send();
                return $this->refresh();
            }
            else{
                Yii::$app->session->setFlash('error', 'Ошибка');
            }
            $this->refresh();
        }
        return $this->render('replenish',compact('replenish','text_pm'));
    }

    public function actionOutput(){
        $output = new Orders();
        $text_pm = RedactionText::find()->select('payment_system')->one();
        if($output->load(Yii::$app->request->post())) {
            $output->type = 'Вывод';
            $output->payment_system = $_POST['pay_system'];
            $user = User::find()->where(['email' => $output->email])->select(['id','email'])->one();
            if ($user->email != null)
            {
                $output->is_user = $user->id;
            }
            else {
                $output->is_user = 0;
            }
            if(!isset($_POST['is_confirm'])){
                Yii::$app->session->setFlash('error', 'Вы не согласились на обработку данных.');
                return $this->refresh();
            }
            if($output->save()){
                Yii::$app->session->setFlash('success', 'Спасибо, ваша заявка принята.');
                $output->email = \Yii::$app->mailer->compose()
                    ->setTo('zhenja1509@gmail.com')
                    ->setFrom('zhenja94@bk.ru')
                    ->setSubject('Заявка на '.$output->type)
                    ->setTextBody("Пользователь $output->name,  email: $output->email, телефон: $output->phone оставил заявку на: 
                        $output->type,  платежной системой $output->payment_system")
                    ->send();
                return $this->refresh();
            }
        else{
                Yii::$app->session->setFlash('error', 'Ошибка');
            }
            $this->refresh();
        }
        return $this->render('output', compact('output','text_pm'));
    }

    public function actionInformation(){

        return $this->render('information');
    }
    public function actionContacts(){
        $feedback = new Feedback();
        if ($feedback->load(Yii::$app->request->post())) {
            if($feedback->save()){
                $feedback->email = \Yii::$app->mailer->compose()
                    ->setTo('zhenja1509@gmail.com')
                    ->setFrom('zhenja94@bk.ru')
                    ->setSubject('Обратная связь')
                    ->setTextBody("Пользователь $feedback->name,  $feedback->email, телефон: $feedback->telefon оставил обратную связь: $feedback->text")
                    ->send();
                $this->refresh();
            }
        }else {
            false;
        }
        return $this->render('contacts',compact('feedback'));
    }
    public function actionAllPosts(){
        $query = Posts::find();
        $pages = new Pagination(['totalCount' => $query->count(), 'pageSize' => 6, 'forcePageParam' => false, 'pageSizeParam'=>false]);
        $posts = $query->offset($pages->offset)->orderBy(['date' => SORT_DESC])->limit($pages->limit)->all();
        return $this->render('all-posts',compact('posts','pages'));
    }

    public function actionSinglePost($id){
        $blogs = Posts::findOne($id);
        $blogs_prew = Posts::find()->select(['id','title','image'])->where(['<', 'id', $id])->orderBy(['id' => SORT_DESC])->limit(1)->one();
        $blogs_next = Posts::find()->select(['id','title'])->where(['>', 'id', $id])->orderBy(['id' => SORT_DESC])->limit(1)->one();
        $related_blogs = Posts::find()->orderBy(['date' => SORT_DESC])->limit(3)->all();
        return $this->render('single-post', compact('blogs','related_blogs', 'blogs_prew', 'blogs_next'));
    }

}

views/layouts/exchanger.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use yii\widgets\ActiveForm;
use app\widgets\SubNewsWidget;
AppAsset::register($this);
?>
<?php $this->beginPage() ?>


<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- TITLE -->
    <?php if(Yii::$app->language == 'ru'):  ?>
        <title>Обменник Webmoney (вебмани) на наличные в Москве. Удобные способы пополнения Webmoney</title>
    <?php endif;?>
    <?php if(Yii::$app->language == 'en'):  ?>
        <title>"Green Cash" - profitable e-money exchange</title>
    <?php endif;?>
    <!-- FAVICON -->
    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />
    <!-- Bootstrap -->

    <!-- GOOGLE FONT -->
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,800,900' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>


<div class="outslider_loading">
    <div class="outslider_loader"></div>
</div>
<header class="header-area navbar-fixed-top">
    <div class="container custom-header">
        <div class="row">
            <div id="menuzord" class="menuzord">
                <a href="/" class="menuzord-brand"><img src="/web/images/logo.png" alt=""></a>


                <ul class="menuzord-menu menuzord-menu-bg">
                    <li><a href="/"><?=Yii::t('common','Главная')?></a></li>
                    <li><a href="/page/replenish"><?=Yii::t('common','Пополнить')?></a></li>
                    <li><a href="/page/output"><?=Yii::t('common','Вывести')?></a></li>
                    <li><a href="/page/all-posts"><?=Yii::t('common','Блоги')?></a>
                    <li><a href="http://wiki.webmoney.ru/projects/webmoney/wiki/Условия_для_обменных_пунктов"><?=Yii::t('common','Информация')?></a>

                         <!--<ul class="dropdown">
                            <li><a ">Информация</a></li>
                           <li><a href="shop-product.html">Правила системы</a></li>
                            <li><a href="shop-single-product.html">Что такое WebMoney</a></li>
                            <li><a href="shoping-cart.html">Уведомление о рисках</a></li>
                            <li><a href="shoping-cart.html">Получение аттестатов</a></li>
                            <li><a href="shoping-cart.html">Соглашение с WebMoney</a></li>
                        </ul>-->

                    </li>
                    <li><a href="/page/contacts"><?=Yii::t('common','Контакты')?></a></li>

                    <li><?= Html::a('en', ['/', 'language' => 'en']) ?></li>

                    <li><?= Html::a('ru', ['/', 'language' => 'ru']) ?></li>
                </ul>


                <div class="appointment-area">

                    <p><a href="/home/personal-area"><?=Yii::t('common','Личный кабинет')?></a></p>
                </div>
            </div>
        </div>
    </div>
</header>
<?= $content ?>
<?php $this->endBody() ?>

<footer class="footer-area">
    <div class="footer-top-content">
        <div class="container">
            <div class="row">
                <div class="col-sm-3 col-md-3 no-padding">
                    <div class="footer-top-single text-center">
                        <p><?=Yii::t('common','Наши контакты')?></p>
                        <p>тел. +7 (913) 155-09-18</p>

                    </div>
                </div>
                <div class="col-sm-3 col-md-3 no-padding">
                    <div class="footer-top-single footer-top-single-bg-2 text-center">
                        <p>E-mail : GreenCashwm@gmail.com</p>
                        <p>Skype : GreenCashwm</p>
                        <p>Telegram : @GreenCash_wm</p>
                    </div>
                </div>
                <div class="col-sm-3 col-md-3 no-padding">
                    <div class="footer-top-single footer-top-single-bg-2 text-center">
                        <p>WMID: 658251617935</p>
                        <p>R200348960891</p>
                        <p>Z748494898487</p>
                    </div>
                </div>
                <div class="col-sm-3 col-md-3 no-padding">
                    <div class="footer-top-single text-center">
                        <p><?=Yii::t('common','г.Москва')?></p>
                        <p><?=Yii::t('common','ул. Орджоникидзе, д.11, стр.2')?></p>

                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="footer-main-content">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-md-3">
                    <div class="footer-main-single footer-first-content clearfix">
                        <h2><?=Yii::t('common','Режим работы')?></h2>
                        <p>


                        </p>
                        <div class="footer-time">
                            <ul>
                                <li><?=Yii::t('common','С Пн. по Пт.')?></li>
                                <li>8:00 - 16:00</li>
                                <li><?=Yii::t('common','Суббота')?></li>
                                <li>8:00 - 16:00</li>
                                <li><?=Yii::t('common','Воскресенье')?></li>
                                <li><?=Yii::t('common','закрыто')?></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-md-2">
                    <div class="footer-main-single clearfix">
                        <h2><?=Yii::t('common','Услуги')?></h2>
                        <div class="footer-service">
                            <ul>
                                <li><a href="/page/replenish"><?=Yii::t('common','Пополнить')?></a></li>
                                <li><a href="/page/output"><?=Yii::t('common','Вывести')?></a></li>
                                <!--<li><a href="#">Для юр. лиц</a></li>-->
                                <li><a href="#">Тарифы</a></li>

                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-md-2">
                    <div class="footer-main-single footer-third-content clearfix">
                        <h2><?=Yii::t('common','Курсы валют')?></h2>
                        <img src="http://webmoneyexchange.biz/informer/show.php?informer=88x31&cur1=WMR&cur2=WMZ&color=green" height="40" width="120"  alt="Обмен WebMoney" title="Курсы WebMoney WMR-WMZ" border="0" /><br/>
                        <img src="http://webmoneyexchange.biz/informer/show.php?informer=88x31&cur1=WMR&cur2=WME&color=green" height="40" width="120"  alt="Обмен WebMoney" title="Курсы WebMoney WMR-WME" border="1" />
                    </div>
                </div>
                <div class="col-sm-6 col-md-2">
                    <div class="footer-main-single footer-third-content clearfix">
                        <h2><?=Yii::t('common','Аттестован webmoney')?></h2>
                        <a href="https://www.megastock.com/" target="_blank"><img src="https://www.webmoney.ru/img/icons/88x31_wm_blue.png" alt="www.megastock.com" border="0"/></a>
                        <a href="https://passport.webmoney.ru/asp/certview.asp?wmid=658251617935" target="_blank">
                            <img src="https://www.webmoney.ru/img/icons/88x31_wm_blue.png" alt="Здесь находится аттестат нашего WM идентификатора 658251617935" border="0" /><br />
                            <span style="font-size: 0,7em;">Проверить аттестат</span></a>
                    </div>
                </div>
                <div class="col-sm-6 col-md-3">
                    <div class="footer-main-single footer-first-content f-fourth-content clearfix">
                        <h2><?=Yii::t('common','Подписаться на новости')?></h2>
                        <p><?=Yii::t('common','Не пропустите важную информацию о электронных деньгах')?>.</p>
                        <?= SubNewsWidget::widget();?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom-content-details">
        <div class="container">
            <div class="row">
                <div class="footer-bottom-content">
                    <div class="col-sm-4 col-md-4 no-padding-left">
                        <div class="footer-bottom-single">
                            <p> © 2017 <?=Yii::t('common','Разработка сайта')?> <a href="http://arkell.ruf">IT - studio Arkell</a></p>
                        </div>
                    </div>
                    <div class="col-sm-4 col-md-4 no-padding">
                        <div class="footer-bottom-single">
                            <div class="footer-menu">
                                <a href="#">О компании</a>
                                <a href="#">Политика конфиденциальности</a>
                                <a href="/page/contacts"><?=Yii::t('common','Контакты')?></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4 col-md-4  no-padding-right">
                        <div class="footer-bottom-single">
                            <ul class="footer-social text-right">
                                <li style="top:30px"> <a href="#" ><i class="fa fa-facebook" ></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                                <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
                                <li><a href="#"> <i class="fa fa-rss"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>




</body>

<?php $this->endPage() ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\models\User;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

//AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/web/css/site.css" rel="stylesheet">
    <?= Html::csrfMetaTags() ?>

    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'GreenCash',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        ['label' => Yii::t('common','Главная'), 'url' => ['/site/index']],
        ['label' => Yii::t('common','Личный кабинет'), 'url' => ['/home/personal-area']],
    ];

    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => Yii::t('common','Войти'), 'url' => ['/site/signup']];
        $menuItems[] = ['label' => Yii::t('common','Регистрация'), 'url' => ['/site/login']];
    } else {
        $menuItems[] = '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                Yii::t('common','Выйти (') . Yii::$app->user->identity->email . ')',
                ['class' => 'btn btn-link logout']
            )
            . Html::endForm()
            . '</li>';
    }

    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<!--<footer class="footer">-->
<!--    <div class="container">-->
<!--        <p class="pull-left">&copy; My Company --><?//= date('Y') ?><!--</p>-->
<!---->
<!--        <p class="pull-right">--><?//= Yii::powered() ?><!--</p>-->
<!--    </div>-->
<!--</footer>-->

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>