controllers/HomeController.php
<?php
/**
 * Created by PhpStorm.
 * User: zhenj
 * Date: 21.07.2017
 * Time: 14:35
 */

namespace app\controllers;

use app\models\Feedback;
use app\models\Orders;
use app\models\RedactionText;
use app\models\Sliders;
use app\models\SubscriptionNews;
use app\models\Transactions;
use app\models\User;
use Codeception\Lib\Interfaces\ActiveRecord;
use yii\behaviors\TimestampBehavior;
use yii\data\ActiveDataProvider;
use app\models\Posts;
use app\models\Reviews;
use Yii;
use yii\helpers\StringHelper;
use yii\web\UploadedFile;
use yii\data\Pagination;
class HomeController extends BehaviorsController
{

    public function actionNews(){

        $query = Posts::find();
        $pages = new Pagination(['totalCount'=> $query->count(), 'pageSize'=>5,
          'forcePageParam' => false, 'pageSizeParam' => false]);
        $news  = $query->offset($pages->offset)->limit($pages->limit)->all();
        $model = Posts::find()->orderBy(['date' =>SORT_DESC])->all();
        return $this->render('news', compact('news','pages','model'));
    }

    public function actionRedactionText(){

        $redaction = RedactionText::find()->where(['id' => 1])->one();
        if ($redaction->load(Yii::$app->request->post())) {
            $redaction->text;
            $redaction->save();
            $this->refresh();
        }else {
            false;
        }
        return $this->render('redaction-text',compact('redaction'));
    }
    public function actionSortNews($id){
        $this->layout=false;

        $model = Posts::findOne($id);

        return $this->render('sort-news', compact('model'));
    }

    public function actionPersonalArea(){
        $this->view->title = Yii::t('common','Личный кабинет');
        $user = User::find()->select('email')->all();
        $sub_news = SubscriptionNews::find()->where(['email' => $user])->one();
        if ($sub_news == null)
        {
            $is_subNews = 0;
        }
        else{
            $is_subNews = 1;
        }
        $sub_news_save = new SubscriptionNews();
        if ($sub_news_save->load(Yii::$app->request->post())){
            if ($sub_news_save->save()){
                $sub_news_save->email = \Yii::$app->mailer->compose()
                    ->setTo('zhenja1509@gmail.com')
                    ->setFrom('zhenja94@bk.ru')
                    ->setSubject('Подписка на новости')
                    ->setTextBody("На ваши новости подписался " .$sub_news->email)
                    ->send();
            }
            $this->refresh();
        }
        $order = new Orders();
        if($order->load(Yii::$app->request->post())) {
            $order->is_user = Yii::$app->user->identity->id;
            if(!isset($_POST['is_confirm'])){
                Yii::$app->session->setFlash('error', 'Вы не согласились на обработку данных.');
                return $this->refresh();
            }
            if($order->save()){
                Yii::$app->session->setFlash('success', 'Спасибо, ваша заявка принята.');
                $order->email = \Yii::$app->mailer->compose()
                    ->setTo('zhenja1509@gmail.com')
                    ->setFrom('zhenja94@bk.ru')
                    ->setSubject('Заявка на '. $order->type)
                    ->setTextBody("Пользователь $order->name,  email: $order->email, телефон: $order->phone оставил заявку на: 
                        $order->type,  платежной системой $order->payment_system")
                    ->send();
                return $this->refresh();
            }
            else{
                Yii::$app->session->setFlash('error', 'Ошибка');
            }
            $this->refresh();
        }
        $history_orders = new ActiveDataProvider([
            'query' => Orders::find()->where(['is_user' => Yii::$app->user->identity->id]),
            'pagination' => [
                'pageSize' => 5,
            ],
        ]);

        return $this->render('personal-area',compact('history_orders','is_subNews','sub_news_save','order'));
    }


    public function actionAdminPanel(){
        $this->view->title = "Панель админа";
        $subNews = new ActiveDataProvider([
            'query' => SubscriptionNews::find(),
            'pagination' => [
                'pageSize' => 5,
            ],
        ]);
        $feedBack = new ActiveDataProvider([
            'query' => FeedBack::find(),
            'pagination' => [
                'pageSize' => 5,
            ],
        ]);
        $orders = new ActiveDataProvider([
            'query' => Orders::find()->with('user'),
            'pagination' => [
                'pagesize' => 10,
            ],
        ]);

        $transactions = new ActiveDataProvider([
            'query' => Transactions::find(),
            'pagination' => [
                'pagesize' => 10,
            ],
        ]);


        return $this->render('admin-panel',compact('subNews','orders', 'transactions', 'feedBack'));
    }
    public function actionDeleteOrders($id){
        $orders = Orders::findOne($id)->delete();
        $this->redirect('/home/admin-panel');
    }
    public function actionDeleteFeedback($id){
        $feedBack = FeedBack::findOne($id)->delete();
        $this->redirect('/home/admin-panel');
    }
    public function actionDeleteSubnews($id){
        $subNews = SubscriptionNews::findOne($id)->delete();
        $this->redirect('/home/admin-panel');
    }
    public function actionDeleteTransactions($id){
        $transactions = Transactions::findOne($id)->delete();
        $this->redirect('/home/admin-panel');
    }
    public function actionAddPosts(){
        $posts = new Posts();
        $users = User::find()->select('email')->all();
        if ($posts->load(Yii::$app->request->post())) {
            if(Yii::$app->request->isPost){
                $posts->image = UploadedFile::getInstance($posts, 'image');
                $posts->date = Yii::$app->formatter->asDate(date('Y-m-d'));
                $posts->image = $posts->upload();
            }
            if($posts->save()){
                Yii::$app->session->setFlash('success', 'Новость сохранена.');
            }
            if (isset($_POST['send_out'])){
                foreach ($users as $user){
                Yii::$app->mailer->compose()
                    ->setTo($user->email)
                    ->setFrom('zhenja94@bk.ru')
                    ->setSubject('GreenCash '.$posts->title)
                    ->setTextBody("Вы получили это сообщение так как зарегистрированы на GreenCash. "
                        .strip_tags($posts->text))
                    ->send();
                }
                Yii::$app->session->setFlash('success', 'Новость разослана на email пользователей.');
            }
            $this->refresh();
        }else {
            false;
        }

        return $this->render('add-posts', compact('posts'));
    }


    public function actionAddSliders(){
        $sliders = new Sliders();
        if ($sliders->load(Yii::$app->request->post())) {
            if(Yii::$app->request->isPost){
                $sliders->image = UploadedFile::getInstance($sliders, 'image');
                $sliders->image = $sliders->upload();
            }
            $sliders->save();
            $this->goHome();
        }else {
            false;
        }
        return $this->render('add-sliders',compact('sliders'));
    }
    public function actionUpdateSlider($id){
        $sliders = Sliders::find()->where(['id'=>$id])->one();
        if ($sliders->load(Yii::$app->request->post())) {
            $sliders->save();
            $this->redirect('/home/change-posts');
        }
        else{
            false;
        }
        return $this->render('update-slider',compact('sliders'));
    }
    public function actionDeleteSlider($id){
        $sliders = Sliders::findOne($id)->delete();
         $this->redirect('/home/change-posts');
    }



    public function actionChangePosts(){
        $posts = new ActiveDataProvider([
            'query' => Posts::find(),
            'pagination' => [
                'pagesize' => 5,
            ],
        ]);
         $reviews = new ActiveDataProvider([
            'query' => Reviews::find(),
            'pagination' => [
                'pagesize' => 10,
            ],
        ]);
        $sliders = new ActiveDataProvider([
            'query' => Sliders::find(),
            'pagination' => [
                'pagesize' => 10,
            ],
        ]);
        return $this->render('change-posts', compact('posts','reviews','sliders'));
    }

    public function actionAddReviews(){
        $reviews = new Reviews();
        if ($reviews->load(Yii::$app->request->post())){
            $reviews->save();
            $this->redirect('/home/admin-panel');
        }
        return $this->render('add-reviews', compact('reviews'));
    }
     public function actionDeletePosts($id){
        $posts = Posts::findOne($id)->delete();
        $this->redirect('/home/change-posts');

     }
     public function actionDeleteReviews($id){
        $reviews = Reviews::findOne($id)->delete();
        $this->redirect('/home/change-posts');
     }
     public function actionUpdateReviews($id){
        $reviews = Reviews::find()->where(['id'=>$id])->one();
        if ($reviews->load(Yii::$app->request->post())) {
            $reviews->save();
            $this->redirect('/home/change-posts');
        }
        else{
            false;
        }
        return $this->render('update-reviews', compact('reviews'));
     }
    public function actionUpdatePosts($id){
        $posts = Posts::find()->where(['id' => $id])->one();
        if ($posts->load(Yii::$app->request->post())) {

views/home/add-posts.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use dosamigos\tinymce\TinyMce;

?>
<div class="panel panel-primary col-md-12 center-block">
    <div class="panel-heading text-center"><h4>Добавление новости</h4></div>
    <div class="panel-body">
        <?php if (Yii::$app->session->hasFlash('success')): ?>
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <?php echo Yii::$app->session->getFlash('success'); ?>
            </div>
        <?php endif;?>

        <?php if (Yii::$app->session->hasFlash('error')): ?>
            <div class="alert alert-danger alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <?php echo Yii::$app->session->getFlash('error'); ?>
            </div>
        <?php endif;?>
        <?$form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>
        <?=$form-> field($posts, 'title')->textInput();?>
        <?=$form-> field($posts, 'image')->fileInput();?>
        <?= $form->field($posts, 'text')->widget(TinyMce::className(), [
            'options' => ['rows' => 10],
            'language' => 'ru',
            'clientOptions' => [
                'plugins' => [
                    'advlist autolink lists link charmap hr preview pagebreak',
                    'searchreplace wordcount textcolor visualblocks visualchars code fullscreen nonbreaking',
                    'save insertdatetime media table contextmenu template paste image responsivefilemanager filemanager',
                ],
                'toolbar' => 'undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | responsivefilemanager link image media',
                'external_filemanager_path' => '/web/plugins/responsive_filemanager/filemanager/',
                'filemanager_title' => 'Responsive Filemanager',
                'external_plugins' => [
                    //Иконка/кнопка загрузки файла в диалоге вставки изображения.
                    'filemanager' => '/web/plugins/responsive_filemanager/filemanager/plugin.min.js',
                    //Иконка/кнопка загрузки файла в панеле иснструментов.
                    'responsivefilemanager' => '/web/plugins/responsive_filemanager/tinymce/plugins/responsivefilemanager/plugin.min.js',
                ],
                'relative_urls' => false,
            ]
        ]);?>
        <?= $form->field($posts, 'category')->radioList(['Блог'=> 'Блог','Новость'=> 'Новость' ])->label('Категория');?>

        <input type="checkbox" name="send_out" > Разослать пользователям
        <p> <br/><?= Html::submitButton('Добавить', ['class'=>'btn btn-success']) ?></p>

        <? ActiveForm::end(); ?>
    </div>
</div>



views/home/add-reviews.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
 ?>

 <div class="panel panel-primary col-md-12 center-block">
    <div class="panel-heading text-center"><h4>Добавление отзывов</h4></div>
    <div class="panel-body">
        <?$form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>
        <?=$form-> field($reviews, 'name')->textInput();?>
        <?=$form-> field($reviews, 'position')->textInput();?>
        <?= $form->field($reviews, 'text')->textarea();?>
        <?= Html::submitButton('Добавить', ['class'=>'btn btn-success']) ?>
        <? ActiveForm::end(); ?>
    </div>
</div>

views/home/add-sliders.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use dosamigos\tinymce\TinyMce;
?>
<div class="panel panel-primary col-md-12 center-block">
    <div class="panel-heading text-center"><h4>Добавление слайдера</h4></div>
    <div class="panel-body">
        <?$form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>
        <?=$form-> field($sliders, 'image')->fileInput();?>
        <?= $form->field($sliders, 'text')->widget(TinyMce::className(), [
            'options' => ['rows' => 10],
            'language' => 'ru',
            'clientOptions' => [
                'plugins' => [
                    'advlist autolink lists link charmap hr preview pagebreak',
                    'searchreplace wordcount textcolor visualblocks visualchars code fullscreen nonbreaking',
                    'save insertdatetime media table contextmenu template paste image responsivefilemanager filemanager',
                ],
                'toolbar' => 'undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | responsivefilemanager link image media',
                'external_filemanager_path' => '/web/plugins/responsive_filemanager/filemanager/',
                'filemanager_title' => 'Responsive Filemanager',
                'external_plugins' => [
                    //Иконка/кнопка загрузки файла в диалоге вставки изображения.
                    'filemanager' => '/web/plugins/responsive_filemanager/filemanager/plugin.min.js',
                    //Иконка/кнопка загрузки файла в панеле иснструментов.
                    'responsivefilemanager' => '/web/plugins/responsive_filemanager/tinymce/plugins/responsivefilemanager/plugin.min.js',
                ],
                'relative_urls' => false,
            ]
        ]);?>
        <?= Html::submitButton('Добавить', ['class'=>'btn btn-success']) ?>
        <? ActiveForm::end(); ?>
    </div>
</div>

views/home/admin-panel.php
<?php
use yii\grid\GridView;
use yii\helpers\Html;
 ?>


<div class="navbar navbar-inverse">
    <ul class="nav nav-tabs nav-justified">
        <li><a href="/home/add-posts"><h5>Добавить новость</h5></a> </li>
         <li><a href="/home/add-reviews"><h5>Добавить отзыв</h5></a> </li>
        <li><a href="/transactions/exchang"><h5>Перевести деньги</h5></a> </li>
        <li><a href="/home/add-sliders"><h5>Добавить слайд</h5></a> </li>
        <li><a href="/home/redaction-text"><h5>Редактирование текста/платеж.систем</h5></a> </li>
        <li><a href="/home/change-posts"><h5>Редактирование/удаление новостей, отзывов, слайдов</h5></a> </li>
    </ul>
</div>

<div class="row">
    <div class="col-md-4 col-sm-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Подписавшиеся на новости</h3>
            </div>
            <div class="panel-body">
                <?php
                echo GridView::widget([
                    'dataProvider' => $subNews,
                    'columns' => [
                        ['class' => 'yii\grid\SerialColumn'],
                        'id',
                        'email:ntext',
                        ['class' => 'yii\grid\ActionColumn',
                            'header' => 'Действия',
                            'template' => '{delete}{link}',
                            'buttons' => [
                                'delete' => function( $url,$model){
                                    $customUrl = Yii::$app->getUrlManager()->createUrl(['home/delete-subnews','id'=> $model->id]);
                                    return Html::a('Удалить',$customUrl);
                                },

                            ],
                        ],
                    ],
                ]);
                ?>
            </div>
        </div>
    </div>

    <div class="col-md-8 col-sm-8">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Обратная связь</h3>
            </div>
            <div class="panel-body">
                <?php
                echo GridView::widget([
                    'dataProvider' => $feedBack,
                    'columns' => [
                        ['class' => 'yii\grid\SerialColumn'],
                        'id',
                        'name:ntext',
                        'email:ntext',
                        'telefon:ntext',
                        'title:ntext',
                        'text:ntext',
                        ['class' => 'yii\grid\ActionColumn',
                            'header' => 'Действия',
                            'template' => '{delete}{link}',
                            'buttons' => [
                                'delete' => function( $url,$model){
                                    $customUrl = Yii::$app->getUrlManager()->createUrl(['home/delete-feedback','id'=> $model->id]);
                                    return Html::a('Удалить',$customUrl);
                                },

                            ],
                        ],
                    ],
                ]);
                ?>
            </div>
        </div>
    </div>
</div>
<!---->
<div class="panel panel-primary" >
    <div class="panel-heading">
        <h3 class="panel-title">Заявки</h3>
    </div>
    <div class="panel-body">
        <?php
        echo GridView::widget([
            'dataProvider' => $orders,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                'id',
                [
                    'attribute'=>'name',
                    'label'=>'Имя',
                ],

                'email:ntext',
                'phone:ntext',
                'type:ntext',
                'payment_system:ntext',
                'is_user:ntext',
                [
                    'attribute'=>'user.email',
                    'label'=>'Зарегистрированный или нет',
                ],

                ['class' => 'yii\grid\ActionColumn',
                    'header' => 'Действия',
                    'template' => '{delete}{link}',
                    'buttons' => [
                        'delete' => function( $url,$model){
                            $customUrl = Yii::$app->getUrlManager()->createUrl(['/home/delete-orders','id'=> $model->id]);
                            return Html::a('Удалить',$customUrl);
                        },

                    ],
                ],
            ],
        ]);
        ?>

    </div>
</div>
<div class="panel panel-primary" >
    <div class="panel-heading">
        <h3 class="panel-title">Транзакции</h3>
    </div>
    <div class="panel-body">
        <?php
        echo GridView::widget([
            'dataProvider' => $transactions,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                'id',
                [
                    'attribute'=>'wmid',
                    'label'=>'WMID',
                ],
                [
                    'attribute'=>'sender_purse',
                    'label'=>'Кошелек отправки',
                ],
                [
                    'attribute'=>'recipient_purse',
                    'label'=>'Кошелек получателя',
                ],
                [
                    'attribute'=>'number_transaction',
                    'label'=>'Номер транзакции',
                ],
                [
                    'attribute'=>'amount',
                    'label'=>'Сумма',
                ],
                [
                    'attribute'=>'description',
                    'label'=>'Описание',
                ],

                ['class' => 'yii\grid\ActionColumn',
                    'header' => 'Действия',
                    'template' => '{delete}{link}',
                    'buttons' => [
                        'delete' => function( $url,$model){
                            $customUrl = Yii::$app->getUrlManager()->createUrl(['/home/delete-transactions','id'=> $model->id]);
                            return Html::a('Удалить',$customUrl);
                        },

                    ],
                ],
            ],
        ]);
        ?>

    </div>
</div>

views/home/change-posts.php
<?php 
use yii\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;

?>

<div class="row">
    <div class="col-md-12 col-sm-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                 <h3 class="panel-title text-center">Статьи</h3>
             </div>
            <div class="panel-body">
            <?php echo GridView::widget([
                    'dataProvider' => $posts,
                    'columns' => [
                    'title:ntext',
                    'text:raw',
                    'date:ntext',
                    'category:ntext',
                     ['class' => 'yii\grid\ActionColumn',
                            'header' => 'Действия',
                            'template' => '{delete}{link}, {update}{link}',
                            'buttons' => [
                                'delete' => function( $url,$model){
                                    $customUrl = Yii::$app->getUrlManager()->createUrl(['home/delete-posts','id'=> $model->id]);
                                    return Html::a('Удалить',$customUrl);
                                },
                                'update' => function($url, $model){
                                    $customUrl = Yii::$app->getUrlManager()->createUrl(['home/update-posts', 'id' => $model->id]);
                                    return Html::a('Редактировать',$customUrl);
                                }

                            ],
                        ],
                ],
            ]);?>
             
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12 col-sm-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                 <h3 class="panel-title text-center">Отзывы</h3>
             </div>
            <div class="panel-body">
            <?php echo GridView::widget([
                    'dataProvider' => $reviews,
                    'columns' => [
                    'name:ntext',
                    'position:ntext',
                    'text:ntext',
                    ['class' => 'yii\grid\ActionColumn',
                            'header' => 'Действия',
                            'template' => '{delete}{link}, {update}{link}',
                            'buttons' => [
                                'delete' => function( $url,$model){
                                    $customUrl = Yii::$app->getUrlManager()->createUrl(['home/delete-reviews','id'=> $model->id]);
                                    return Html::a('Удалить',$customUrl);
                                },
                                'update' => function($url, $model){
                                    $customUrl = Yii::$app->getUrlManager()->createUrl(['home/update-reviews', 'id' => $model->id]);
                                    return Html::a('Редактировать',$customUrl);
                                }

                            ],
                        ],
            
                ],
            ]);?>
            
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-sm-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title text-center">Отзывы</h3>
            </div>
            <div class="panel-body">
                <?php echo GridView::widget([
                    'dataProvider' => $sliders,
                    'columns' => [
                        [
                            'label' => 'Картинка',
                            'format' => 'raw',
                            'value' => function($data){
                                return Html::img(Url::toRoute($data->image),[
//
                                    'style' => 'width:250px;'
                                ]);
                            },
                        ],
                        'text:raw',
                        ['class' => 'yii\grid\ActionColumn',
                            'header' => 'Действия',
                            'template' => '{delete}{link}, {update}{link}',
                            'buttons' => [
                                'delete' => function( $url,$model){
                                    $customUrl = Yii::$app->getUrlManager()->createUrl(['home/delete-slider','id'=> $model->id]);
                                    return Html::a('Удалить',$customUrl);
                                },
                                'update' => function($url, $model){
                                    $customUrl = Yii::$app->getUrlManager()->createUrl(['home/update-slider', 'id' => $model->id]);
                                    return Html::a('Редактировать',$customUrl);
                                }
                            ],
                        ],

                    ],
                ]);?>

            </div>
        </div>
    </div>
</div>

views/home/news.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\LinkPager;
?>
<?php echo '<div>' .LinkPager::widget(['pagination'=>$pages]). '</div>'; ?>
<button type="button" class="up">Показать старые новости</button>
<button type="button" class="down">Показать новые новости</button>

<div class="row">

<?php foreach ($model as $dat): ?>

    <?php $new_date = Yii::$app->formatter->asDate($dat->date, 'd.n.Y');?>
    <div class="row">
        <a href="<?= yii\helpers\Url::to (['home/sort-news', 'id' => $dat->id])?>">
        <button type="button" class="btn btn-default">
            <?= $new_date ?>
        </button>
        </a>
        <br/>
     </div>


    <?php endforeach;?>
</div>



<?php foreach ($news as $new): ?>
    <div id="news" style="text-align: center;">
        <div class="oneNew">
            <a href="<?= yii\helpers\Url::to (['home/delete', 'id' => $new->id])?>" class="btn btn-danger">Delete</a>
            <a href="<?= yii\helpers\Url::to (['home/update', 'id' => $new->id])?>" class="btn btn-success">Update</a>
            <div class="qw1">
                <?= $new->text ?>
            </div>
                <div class="qw">
                    <?=$new->date ?>
                </div>
        </div>
    </div>
<?php endforeach;?>


<?php
$script = <<< JS
 $('.up').click(function() {
           $(".oneNew").sort(function(a,b){
    return new Date($(a).find(".qw").text()) < new Date($(b).find(".qw").text());
})
    .each(function(){
    $("#news").prepend(this);
})
 });

 
 $('.down').click(function() {
           $(".oneNew").sort(function(a,b){
    return new Date($(a).find(".qw").text()) > new Date($(b).find(".qw").text());
})
    .each(function(){
    $("#news").prepend(this);
})
 });
   
   
   
JS;

$this->registerJs($script);
?>

views/home/redaction-text.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\LinkPager;
use dosamigos\tinymce\TinyMce;
?>

<div class="panel panel-primary col-md-12 center-block"">
<div class="panel-heading text-center"><h4>Редактирование текста</h4></div>
<div class="panel-body">
    <?$form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]);?>
    <?= $form->field($redaction, 'text')->widget(TinyMce::className(), [
        'options' => ['rows' => 10],
        'language' => 'ru',
        'clientOptions' => [
            'plugins' => [
                'advlist autolink lists link charmap hr preview pagebreak',
                'searchreplace wordcount textcolor visualblocks visualchars code fullscreen nonbreaking',
                'save insertdatetime media table contextmenu template paste image responsivefilemanager filemanager',
            ],
            'toolbar' => 'undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | responsivefilemanager link image media',
            'external_filemanager_path' => '/web/plugins/responsive_filemanager/filemanager/',
            'filemanager_title' => 'Responsive Filemanager',
            'external_plugins' => [
                //Иконка/кнопка загрузки файла в диалоге вставки изображения.
                'filemanager' => '/web/plugins/responsive_filemanager/filemanager/plugin.min.js',
                //Иконка/кнопка загрузки файла в панеле иснструментов.
                'responsivefilemanager' => '/web/plugins/responsive_filemanager/tinymce/plugins/responsivefilemanager/plugin.min.js',
            ],
            'relative_urls' => false,
        ]
    ]);?>
    <?= $form->field($redaction, 'payment_system')->input('text')?>
    <?= Html::submitButton('Добавить', ['class'=>'btn btn-success']) ?>
    <?php  ActiveForm::end(); ?>
</div>


views/home/sort-news.php
<?php
/**
 * Created by PhpStorm.
 * User: zhenj
 * Date: 28.07.2017
 * Time: 17:08
 */

 ?>
<div id="news" style="text-align: center;">
    <div class="oneNew">
        <?=  $model->text?>
        <?= $model->date ?>
    </div>
</div>

