controllers/PageController.php
<?php
/**
 * Created by PhpStorm.
 * User: zhenj
 * Date: 09.08.2017
 * Time: 12:50
 */

namespace app\controllers;


use app\models\Feedback;
use app\models\Orders;
use app\models\Posts;
use app\models\RedactionText;
use app\models\User;
use Codeception\Module\Yii2;
use Yii;
use yii\data\Pagination;
use yii\web\Controller;

class PageController extends BehaviorsController
{
    public $layout = '@app/views/layouts/exchanger.php';

    public function actionReplenish(){
        $replenish = new Orders();
        $text_pm = RedactionText::find()->select('payment_system')->one();
        if($replenish->load(Yii::$app->request->post())) {
            $replenish->type = 'Пополнение';
            $replenish->payment_system = $_POST['pay_system'];
            $user = User::find()->where(['email' => $replenish->email])->select(['id','email'])->one();
            if ($user->email != null)
            {
                $replenish->is_user = $user->id;
            }
            else {
                $replenish->is_user = 0;
            }
            if(!isset($_POST['is_confirm'])){
                Yii::$app->session->setFlash('error', 'Вы не согласились на обработку данных.');
                return $this->refresh();
            }
            if($replenish->save()){
                Yii::$app->session->setFlash('success', 'Спасибо, ваша заявка принята.');
                $replenish->email = \Yii::$app->mailer->compose()
                    ->setTo('zhenja1509@gmail.com')
                    ->setFrom('zhenja94@bk.ru')
                    ->setSubject('Заявка на '. $replenish->type)
                    ->setTextBody("Пользователь $replenish->name,  email: $replenish->email, телефон: $replenish->phone оставил заявку на:
                        $replenish->type,  платежной системой $replenish->payment_system")
                    ->send();
                return $this->refresh();
            }
            else{
                Yii::$app->session->setFlash('error', 'Ошибка');
            }
            $this->refresh();
        }
        return $this->render('replenish',compact('replenish','text_pm'));
    }

    public function actionOutput(){
        $output = new Orders();
        $text_pm = RedactionText::find()->select('payment_system')->one();
        if($output->load(Yii::$app->request->post())) {
            $output->type = 'Вывод';
            $output->payment_system = $_POST['pay_system'];
            $user = User::find()->where(['email' => $output->email])->select(['id','email'])->one();
            if ($user->email != null)
            {
                $output->is_user = $user->id;
            }
            else {
                $output->is_user = 0;
            }
            if(!isset($_POST['is_confirm'])){
                Yii::$app->session->setFlash('error', 'Вы не согласились на обработку данных.');
                return $this->refresh();
            }
            if($output->save()){
                Yii::$app->session->setFlash('success', 'Спасибо, ваша заявка принята.');
                $output->email = \Yii::$app->mailer->compose()
                    ->setTo('zhenja1509@gmail.com')
                    ->setFrom('zhenja94@bk.ru')
                    ->setSubject('Заявка на '.$output->type)
                    ->setTextBody("Пользователь $output->name,  email: $output->email, телефон: $output->phone оставил заявку на: 
                        $output->type,  платежной системой $output->payment_system")
                    ->send();
                return $this->refresh();
            }
        else{
                Yii::$app->session->setFlash('error', 'Ошибка');
            }
            $this->refresh();
        }
        return $this->render('output', compact('output','text_pm'));
    }

    public function actionInformation(){

        return $this->render('information');
    }
    public function actionContacts(){
        $feedback = new Feedback();
        if ($feedback->load(Yii::$app->request->post())) {
            if($feedback->save()){
                $feedback->email = \Yii::$app->mailer->compose()
                    ->setTo('zhenja1509@gmail.com')
                    ->setFrom('zhenja94@bk.ru')
                    ->setSubject('Обратная связь')
                    ->setTextBody("Пользователь $feedback->name,  $feedback->email, телефон: $feedback->telefon оставил обратную связь: $feedback->text")
                    ->send();
                $this->refresh();
            }
        }else {
            false;
        }
        return $this->render('contacts',compact('feedback'));
    }
    public function actionAllPosts(){
        $query = Posts::find();
        $pages = new Pagination(['totalCount' => $query->count(), 'pageSize' => 6, 'forcePageParam' => false, 'pageSizeParam'=>false]);
        $posts = $query->offset($pages->offset)->orderBy(['date' => SORT_DESC])->limit($pages->limit)->all();
        return $this->render('all-posts',compact('posts','pages'));
    }

    public function actionSinglePost($id){
        $blogs = Posts::findOne($id);
        $blogs_prew = Posts::find()->select(['id','title','image'])->where(['<', 'id', $id])->orderBy(['id' => SORT_DESC])->limit(1)->one();
        $blogs_next = Posts::find()->select(['id','title'])->where(['>', 'id', $id])->orderBy(['id' => SORT_DESC])->limit(1)->one();
        $related_blogs = Posts::find()->orderBy(['date' => SORT_DESC])->limit(3)->all();
        return $this->render('single-post', compact('blogs','related_blogs', 'blogs_prew', 'blogs_next'));
    }

}

views/page/all-posts.php
<?php

use app\models\User;
use yii\helpers\Html;
use yii\helpers\StringHelper;
use yii\widgets\LinkPager;
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- TITLE -->
    <title>Experts</title>
    <!-- FAVICON -->
    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />
    <!-- Bootstrap -->

</head>
<body>

<div class="page-title-area blog-area-bg">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-md-6">
                <div class="page-title-left">
                    <h2><?=Yii::t('common','Блоги')?></h2>
                </div>
            </div>
            <div class="col-sm-6 col-md-6">
                <div class="page-bredcrumbs-area text-right">
                    <ul  class="page-bredcrumbs">
                        <li><a href="/"><?=Yii::t('common','Главная')?></a></li>
                        <li><a href="/page/all-posts"><?=Yii::t('common','Блоги')?></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- =========================
  END PAGE TITLE SECTION
============================== -->

<!-- =========================
  START BLOG SECTION
============================== -->
<section class="blog-area blog-page-area bg-type-2">
    <div class="blog-content-area">
        <div class="container">
            <div class="row">

                <?php foreach ($posts as $post):?>
                <div class="col-sm-6 col-md-4">
                    <div class="blog-content-single">
                        <div class="blog-img" style="width: 300px; height: 240px;">

                            <? echo Html::img('@web/'.$post->image, ['style' =>'max-width:100%;max-height: 100%;border: 1px solid black'])?>
                            <i class="fa fa-image"></i>
                        </div>
                        <div class="blog-text" style="width: auto; height: 200px;">
                            <ul>
                                <li><?=$post->date ?> </li>
                                <li>
                                    <a href="#"><?=$post->category?></a>

                                </li>
                            </ul>
                            <h2><a href="<?= yii\helpers\Url::to (['page/single-post', 'id' => $post->id])?>"><?=$post->title?></a></h2>
                            <p><?=StringHelper::truncate(preg_replace("/<img[^<]+/u", '',$post->text), 150, '...')?></p>
                            <a href="<?= yii\helpers\Url::to (['page/single-post', 'id' => $post->id])?>"><i class="fa fa-long-arrow-right"></i> <span><?=Yii::t('common','Подробнее')?></span></a>
                        </div>
                    </div>
                </div>
                <?php endforeach;?>

            </div>
        </div>
    </div>

            <?php echo '<div class="text-center">' .LinkPager::widget(['pagination' => $pages]). '</div>';?>
</section>
<!--        <div class="container">-->
<!--            <div class="row">-->
<!--                <div class="col-md-12 expert-pagination blog-pagination text-center clearfix">-->
<!--                    <nav>-->
<!--                        <ul class="pagination">-->
<!--                            <li><a href="#">1</a></li>-->
<!--                            <li><a href="#">2</a></li>-->
<!--                            <li>-->
<!--                                <a href="#" aria-label="Next">-->
<!--                                    <i class="fa fa-long-arrow-right"></i>-->
<!--                                </a>-->
<!--                            </li>-->
<!--                        </ul>-->
<!--                    </nav>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->


</body>
</html>

views/page/contacts.php
<?php
use yii\widgets\ActiveForm;
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- TITLE -->
    <title>Experts</title>
    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />
    <!-- FAVICON -->


</head>
<body>


<div class="page-title-area contact-area">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-md-6">
                <div class="page-title-left">
                    <h2><?=Yii::t('common','Контакты')?></h2>
                </div>
            </div>
            <div class="col-sm-6 col-md-6">
                <div class="page-bredcrumbs-area text-right">
                    <ul  class="page-bredcrumbs">
                        <li><a href="#"><?=Yii::t('common','Главная')?></a></li>
                        <li><a href="#"><?=Yii::t('common','Контакты')?></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- =========================
  END PAGE TITLE SECTION
============================== -->

<!-- =========================
START CONTACT US SECTION
============================== -->
<section class="contact-us-area contact-us-1-area">
    <div class="contact-form">
        <div class="container">
            <div class="row">
                <div class="col-sm-4">
                    <div class="contact-form-3-text">
                        <h2><?=Yii::t('common','Контактная информация')?></h2>
                        <p>Find out about the ways to deal with debts if you are falling behind with day-to-day bills, loan and credit card repayments or other commitments & get some free advice by speaking to one of our financial advisers over the phone? </p>
                        <div class="address-area">
                            <div class="view-location">
                                <h2><?=Yii::t('common','Адрес')?> :</h2>
                                <p><i class="fa fa-map-marker"></i><?=Yii::t('common','г.Москва')?>
                                    <?=Yii::t('common','ул. Орджоникидзе, д.11, стр.2')?></p>
                                <a href="#location"> <?=Yii::t('common','Показать на карте')?></a>
                            </div>
                            <div class="col-md-6 no-padding-left">
                                <div class="address-details">
                                    <h2>Email :</h2>
                                    <span><i class="fa   fa-envelope"></i>GreenCashwm@gmail.com</span>
                                </div>
                            </div>
                            <div class="col-md-6 no-padding-left">
                                <div class="address-details">
                                    <h2><?=Yii::t('common','Телефон')?> :</h2>
                                    <span><i class="fa  fa-phone"></i> +7 (913) 155-09-18</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-8">
                    <div class="contact-form-left contact-form-3 contact-form-right">
                        <h2><?=Yii::t('common','Напишите нам')?></h2>
                        <div class="show_result"></div>
                        <div class="result_message"></div>

                        <? $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]);?>
                        <div class="row">
                            <div class="col-sm-6">
                                <?= $form->field($feedback, 'name')->input('text',
                                    ['placeholder'=>Yii::t('common','Имя'), 'id'=>'Name'])->label(false);?>
                            </div>
                            <div class="col-sm-6">
                                <?= $form->field($feedback, 'email')->input('email',
                                    ['placeholder'=>'Email', 'id'=>'Email'])->label(false);?>
                            </div>
                            <div class="col-sm-6">
                                <?= $form->field($feedback, 'telefon')->input('text',
                                    ['placeholder'=>Yii::t('common','Телефон'), 'id'=>'Phone'])->label(false);?>
                            </div>
                            <div class="col-sm-6">
                                <?= $form->field($feedback, 'title')->input('text',
                                    ['placeholder'=>Yii::t('common','Тема'), 'id'=>'Subject'])->label(false);?>
                            </div>
                            <div class="col-sm-12">
                                <?= $form->field($feedback, 'text')->textarea(
                                    ['placeholder'=>Yii::t('common','Сообщение'), 'id'=>'Message'])->label(false);?>
                            </div>
                            <a name="location"></a>
                            <div class="col-sm-12 text-center">
                                <button type="submit"  class="btn btn-dm"><?=Yii::t('common','Отправить сообщение')?></button>
                            </div>
                        </div>

                        <?php  ActiveForm::end(); ?>


                    </div>
                </div>
            </div>
        </div>
        <div class="maps">
            <script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Ae549fe9927bbba7178e10d77039f36a9f3d26349407800fbef58d0ab9e02ab80&amp;width=100%&amp;height=500&amp;lang=ru_RU&amp;scroll=false"></script>
        </div>

    </div>

</section>

</body>
</html>

views/page/output.php
<?php
use yii\widgets\ActiveForm;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- TITLE -->
    <title>Пополнить</title>
    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />

</head>
<body>
<div class="page-title-area contact-area">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-md-6">
                <div class="page-title-left">
                    <h2><?=Yii::t('common','Заявка на вывод')?></h2>
                </div>
            </div>
            <div class="col-sm-6 col-md-6">
                <div class="page-bredcrumbs-area text-right">
                    <ul  class="page-bredcrumbs">
                        <li><a href="#"><?=Yii::t('common','Главная')?></a></li>
                        <li><a href="#"><?=Yii::t('common','Вывод')?></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>


<section style="background-color: #1bb580;" class="form-area parallax-window" data-parallax="scroll" data-image-src="./images/form-bg.jpg">
    <div class="contact-form">

        <div class="container form-bg">

            <div class="row">
                <?php if (Yii::$app->session->hasFlash('success')): ?>
                    <div class="alert alert-success alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>

                        <?php echo Yii::$app->session->getFlash('success'); ?>
                    </div>
                <?php endif;?>

                <?php if (Yii::$app->session->hasFlash('error')): ?>
                     <div class="alert alert-danger alert-dismissible" role="alert">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <?php echo Yii::$app->session->getFlash('error'); ?>
                     </div>
                <?php endif;?>

                    <div class="col-sm-12">
                        <div class="contact-form-right">
                            <? $form = ActiveForm::begin();?>

                            <div class="row">
                                <div class="col-sm-6">
                                    <?= $form->field($output,'name')->input('text',['placeholder' => Yii::t('common', 'Ваше имя:')])->label(false) ?>
                                </div>
                                <div class="col-sm-6">
                                    <?= $form->field($output,'email')->input('email',['placeholder' => Yii::t('common', 'Ваш Email:')])->label(false) ?>
                                </div>
                                <div class="col-sm-6">
                                    <?= $form->field($output,'phone')->input('text',['placeholder' => Yii::t('common', 'Номер телефона:')])->label(false) ?>
                                </div>
                                <div class="col-sm-6">
                                    <input type="text" readonly class="form-control" placeholder=<?=Yii::t('common', 'Вывод')?>>
                                </div>
                                <div class="col-sm-12">
                                    <?php $c = explode(',', $text_pm->payment_system)  ?>
                                    <select class="option" name="pay_system">
                                        <option value=""><?= Yii::t('common', 'Выберите платежную систему')?></option>

                                        <?php foreach ($c as $m) {

                                            echo '<option value="'.$m.'">'.Yii::t('common', $m).'</option>';
                                        }

                                        ?>
                                    </select>

                                </div>
                                <div class="col-sm-12 text-center">
                                    <button type="submit" class="btn btn-dm"><?=Yii::t('common','Отправить')?></button>
                                </div>
                                <div class="col-sm-12 text-center">
                                    <input type="checkbox" name="is_confirm" checked> Нажимая кнопку отправить я даю своё согласие на обработку моих персональных данных
                                </div>
                            </div>

                            <?php ActiveForm::end();?>
                        </div>

                    </div>

                </div>
            </div>
        </div>
</section>




</body>
</html>


views/page/replenish.php
<?php
use yii\widgets\ActiveForm;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- TITLE -->
    <title>Пополнить</title>
    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />

</head>
<body>
<div class="page-title-area contact-area">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-md-6">
                <div class="page-title-left">
                    <h2><?=Yii::t('common', 'Заявка на пополнение') ?></h2>
                </div>
            </div>
            <div class="col-sm-6 col-md-6">
                <div class="page-bredcrumbs-area text-right">
                    <ul  class="page-bredcrumbs">
                        <li><a href="#"><?=Yii::t('common', 'Главная') ?></a></li>
                        <li><a href="#"><?=Yii::t('common', 'Пополнение') ?></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
        <section style="background-color: #1bb580;" class="form-area parallax-window" data-parallax="scroll" data-image-src="./images/form-bg.jpg">
            <div class="contact-form">
                <div class="container form-bg">
                    <div class="row">
                        <?php if (Yii::$app->session->hasFlash('success')): ?>
                            <div class="alert alert-success alert-dismissible" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <?php echo Yii::$app->session->getFlash('success'); ?>
                            </div>
                        <?php endif;?>

                        <?php if (Yii::$app->session->hasFlash('error')): ?>
                        <div class="alert alert-danger alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <?php echo Yii::$app->session->getFlash('error'); ?>
                            <?php endif;?>
                        </div>
                        <div class="col-sm-12">
                            <div class="contact-form-right">
                                <? $form = ActiveForm::begin();?>
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <?= $form->field($replenish,'name')->input('text',['placeholder' => Yii::t('common', 'Ваше имя:')])->label(false) ?>
                                        </div>
                                        <div class="col-sm-6">
                                            <?= $form->field($replenish,'email')->input('email',['placeholder' => Yii::t('common', 'Ваш Email:')])->label(false) ?>
                                        </div>
                                        <div class="col-sm-6">
                                            <?= $form->field($replenish,'phone')->input('text',['placeholder' => Yii::t('common', 'Номер телефона:')])->label(false) ?>
                                        </div>
                                        <div class="col-sm-6">
                                            <input type="text" readonly class="form-control" placeholder=<?=Yii::t('common', 'Пополнение')?>>
                                        </div>
                                        <div class="col-sm-12">
                                            <?php $c = explode(',', $text_pm->payment_system)  ?>
                                            <select class="option" name="pay_system">
                                                <option value=""><?= Yii::t('common', 'Выберите платежную систему')?></option>

                                                <?php foreach ($c as $m) {

                                                    echo '<option value="'.$m.'">'.Yii::t('common', $m).'</option>';
                                                }

                                                ?>
                                            </select>

                                        </div>
                                        <div class="col-sm-12 text-center">
                                            <button type="submit" class="btn btn-dm"><?=Yii::t('common', 'Отправить')?></button>
                                        </div>
                                        <div class="col-sm-12 text-center">
                                            <input type="checkbox" name="is_confirm" checked> Нажимая кнопку отправить я даю своё согласие на обработку моих персональных данных
                                        </div>
                                    </div>
                                <?php ActiveForm::end();?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
</body>
</html>


views/page/single-post.php


<?php
use yii\helpers\Html;
use yii\widgets\ActiveField;
use yii\widgets\ActiveForm;

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- TITLE -->
    <title>Experts</title>


    <![endif]-->
</head>
<body>


<div class="page-title-area blog-area-bg">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-md-6">
                <div class="page-title-left">
                    <h2><?=Yii::t('common','Отдельная статья')?></h2>
                </div>
            </div>
            <div class="col-sm-6 col-md-6">
                <div class="page-bredcrumbs-area text-right">
                    <ul  class="page-bredcrumbs">
                        <li><a href="/"><?=Yii::t('common','Главная')?></a></li>
                        <li><a href="/page/all-posts"><?=Yii::t('common','Блоги')?></a></li>
                        <li><a href="#"><?=Yii::t('common','Отдельная статья')?></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<section class="blog-area blog-page-area bg-type-2">
    <div class="container">
        <div class="row">
            <div class="col-md-offset-2 col-md-8">

                <div class="single-blog-content-area">
                    <div class="blog-content-single blog-content-single-no-btm-padding">
                        <div class="blog-img">
                            <? echo Html::img('@web/'.$blogs->image)?>
                            <i class="fa fa-image"></i>
                        </div>
                        <div class="blog-text">
                            <ul>
                                <li><?=$blogs->date ?> </li>
                                <li>
                                    <a href="#"><?=$blogs->category?></a>

                            </ul>
                            <h2><?=$blogs->title?></h2>
                            <p><?=$blogs->text ?></p>


                        </div>
                    </div>
                </div>

                <div class="blog-prev-next clearfix">
                    <div class="blog-prev">
                        <div class="blog-prev-content">
                            <p><?=Yii::t('common','Предыдущая статья')?></p>
                            <?php if ($blogs_prew->id != null):?>
                                <h3><a href="<?= yii\helpers\Url::to (['page/single-post', 'id' => $blogs_prew->id])?>"><?=$blogs_prew->title?></a></h3>
                            <?php endif;?>


                            <div class="prev-left">
                                <a href="#"><img src="/web/images/blog-siderbar-author-1.png" alt=""></a>
                            </div>
                        </div>
                    </div>
                    <div class="blog-next text-right">
                        <div class="blog-next-content">
                            <p><?=Yii::t('common','Следующая статья')?></p>
                            <?php if ($blogs_next->id != null):?>
                                <h3><a href="<?= yii\helpers\Url::to (['page/single-post', 'id' => $blogs_next->id])?>"><?=$blogs_next->title?></a></h3>
                            <?php endif;?>
                            <div class="next-right">
                                <a href="#"><img src="/web/images/blog-siderbar-author-1.png" alt=""></a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="blog-siderbar-area single-blog-thumbnail single-blog-thumbnail-c-padding clearfix">
                    <h2><?=Yii::t('common','Похожии статьи')?></h2>
                    <?php foreach ($related_blogs as $related_blog):?>
                        <div class="col-sm-12 col-sm-4 col-md-4 ">
                            <div class="blog-content-single blog-content-single-no-m-btm">
                                <div class="blog-img" style="width: 209px; height: 167px;">
                                    <? echo Html::img('@web/'.$related_blog->image, ['style' =>'max-width:100%;max-height: 100%'])?>
                                    <i class="fa fa-image"></i>
                                </div>
                                <div class="blog-text">
                                    <ul>
                                        <li><?=$related_blog->date?> </li>
                                    </ul>
                                    <h2><a href="<?= yii\helpers\Url::to (['page/single-post', 'id' => $related_blog->id])?>"><?=$related_blog->title?></a></h2>
                                </div>
                            </div>
                        </div>
                    <?php endforeach;?>


                </div>

            </div>
        </div>
</section>


</body>
</html>
